Repository XanaduAI/flamingpy, pull requests merged in 2022-07, with the labels that each got.

#98 [Frozen Period] Special Release, June 2022
  .github/CHANGELOG.md
  .gitignore
  .local_plt/.gitignore
  flamingpy/_version.py
  flamingpy/simulations.py
  setup.py
  tests/frontend/test_simulations.py
Labels: special release

#104 [Hotfix] Add random number generator where missing CVMacroLayer
  .github/CHANGELOG.md
  flamingpy/_version.py
  flamingpy/noise/cv.py
Labels: bug

#105 Update `getting_started` documentation 📘
  .github/CHANGELOG.md
  doc/index.rst
  doc/tutorials/run_getting_started.py
  doc/usage/getting_started.rst
Labels: documentation

#107 Downgrade `pylint` and remove `pylint` CI workflow
  .github/CHANGELOG.md
  .github/workflows/linting.yaml
  dev_requirements.txt
  flamingpy/_version.py
Labels: bug, chores

#109 Update FlamingPy logo
  .github/CHANGELOG.md
  README.md
  doc/_static/flamingpy_logo_dark.svg
  doc/_static/flamingpy_logo_light.svg
  flamingpy/_version.py
Labels: documentation

#110 [Frozen Period] July 2022 Release
  .github/CHANGELOG.md
  doc/source/fp.rst
  flamingpy/_version.py
Labels: special release
