Repository XanaduAI/flamingpy, pull requests merged in 2022-08, with the labels that each got.

#111 Improving `simulations.py` input options
  .github/CHANGELOG.md
  flamingpy/_version.py
  flamingpy/decoders/decoder.py
  flamingpy/simulations.py
  tests/frontend/test_simulations.py
Labels: breaking feature

#100 Add `add_qubit` and `remove_qubit` functions
  .github/CHANGELOG.md
  flamingpy/__init__.py
  flamingpy/_version.py
  flamingpy/codes/graphs/egraph.py
  tests/qubit_codes/test_graphstates.py
Labels: compatible feature

#103 Plotly visualization 👨🏼‍🎨
  .github/CHANGELOG.md
  dev_requirements.txt
  doc/dev_requirements.txt
  flamingpy/_version.py
  flamingpy/codes/graphs/egraph.py
  flamingpy/codes/surface_code.py
  flamingpy/noise/cv.py
  flamingpy/utils/viz.py
  tests/utils/test_viz.py
Labels: visualization

#116 [Hotfix] Update docformatter version
  .github/CHANGELOG.md
  dev_requirements.txt
  doc/development/guide_for_devs.rst
  flamingpy/_version.py
Labels: documentation

#118 [HOTFIX] Update `setup.py` to allow `git` installation with `pip`
  .github/CHANGELOG.md
  flamingpy/_version.py
  setup.py
Labels: setup

#119 [Frozen Period] Special Release, August 2022
  .github/CHANGELOG.md
  .github/workflows/build_tests.yaml
  .github/workflows/docs.yaml
  .github/workflows/upload_linux_x64.yaml
  .github/workflows/upload_macos_x64.yaml
  .github/workflows/upload_win_x64.yaml
  .gitignore
  README.md
  dev_requirements.txt
  doc/dev_requirements.txt
  doc/development/guide_for_devs.rst
  doc/install.rst
  flamingpy/_version.py
  flamingpy/cpp/cpp_mc_loop.pyx
  setup.py
Labels: special release

#122 [Hotfix] Deletion of remaining Cython lines
  .github/CHANGELOG.md
  flamingpy/__init__.py
  flamingpy/_version.py
  tests/decoders/test_matching.py
  tests/frontend/test_init.py
Labels: chores
