Repository XanaduAI/flamingpy, pull requests merged in 2022-05, with the labels that each got.

#18 [Frozen Period] Special Release April 2022
  .coveragerc
  .github/CHANGELOG.md
  .github/pull_request_template.md
  README.md
  doc/dev_requirements.txt
  doc/development/guide_for_devs.rst
  flamingpy/_version.py
Labels: special release, owners review ready

#14 Improve test coverage
  .coveragerc
  .github/CHANGELOG.md
  .github/workflows/build_tests.yaml
  flamingpy/__init__.py
  flamingpy/_version.py
  flamingpy/benchmarks/decoding.py
  flamingpy/benchmarks/lemon.py
  flamingpy/benchmarks/matching.py
  flamingpy/benchmarks/shortest_path.py
  flamingpy/benchmarks/simulations.py
  flamingpy/decoders/mwpm/lemon.py
  flamingpy/examples/decoding.py
  flamingpy/examples/surface_code.py
  flamingpy/simulations.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_graphstates.py
  tests/unit/test_iid_noise.py
  tests/unit/test_init.py
  tests/unit/test_simulations.py
Labels: workflow & tests

#30 [Frozen Period] Emergency Release, May 2022
  .coveragerc
  .github/CHANGELOG.md
  README.md
  codecov.yml
  doc/_static/RHG_matching.svg
  doc/source/fp.decoders.rst
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/decoders/decoder.py
  flamingpy/examples/decoding.py
  flamingpy/examples/graphstates.py
  flamingpy/examples/macro_reduce.py
  flamingpy/examples/surface_code.py
  flamingpy/utils/viz.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_decoder.py
  tests/unit/test_macro_reduce.py
  tests/unit/test_stabilizer_graph.py
  tests/unit/test_surface_code.py
  tests/unit/test_uf_decoder.py
Labels: breaking feature

#51 fix CodeFactor issues 🪛
  .github/CHANGELOG.md
  .gitignore
  doc/_ext/edit_on_github.py
  doc/tutorials/run_error_correction.py
  flamingpy/_version.py
  flamingpy/decoders/mwpm/algos.py
  flamingpy/decoders/unionfind/algos.py
  flamingpy/decoders/unionfind/uf_classes.py
  flamingpy/examples/surface_code.py
  flamingpy/simulations.py
  flamingpy/utils/viz.py
  tests/conftest.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_simulations.py
  tests/unit/test_uf_decoder.py
Labels: chores

#44 Minor change in surface code example file
  .github/CHANGELOG.md
  doc/conf.py
  doc/tutorials/run_error_correction.py
  doc/tutorials/run_graph_states.py
  flamingpy/_version.py
  flamingpy/examples/surface_code.py
  tests/unit/test_benchmarks_examples.py
Labels: programming conventions

#32 Add more `EGraph` edge and node color options
  .github/CHANGELOG.md
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/cv/ops.py
  flamingpy/decoders/unionfind/uf_classes.py
  flamingpy/examples/decoding.py
  flamingpy/utils/viz.py
  tests/unit/test_benchmarks_examples.py
Labels: visualization

#42 Rethinking the `dims` parameter in `draw_EGraph`
  .github/CHANGELOG.md
  doc/tutorials/run_graph_states.py
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/examples/graphstates.py
  flamingpy/utils/viz.py
Labels: visualization

#47 MPI feature is enabled for `simulations.py` in a non-intrusive manner
  .github/CHANGELOG.md
  .github/pull_request_template.md
  .github/workflows/build_tests.yaml
  .github/workflows/docs.yaml
  .github/workflows/linting.yaml
  .github/workflows/upload_linux_x64.yaml
  .pylintrc
  README.md
  dev_requirements.txt
  doc/_ext/edit_on_github.py
  doc/conf.py
  doc/development/guide_for_devs.rst
  doc/source/fp.rst
  doc/tutorials/run_error_correction.py
  flamingpy/__init__.py
  flamingpy/_version.py
  flamingpy/cv/macro_reduce.py
  flamingpy/cv/ops.py
  flamingpy/decoders/mwpm/algos.py
  flamingpy/decoders/unionfind/algos.py
  flamingpy/decoders/unionfind/uf_classes.py
  flamingpy/examples/decoding.py
  flamingpy/examples/surface_code.py
  flamingpy/simulations.py
  tests/conftest.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_simulations.py
  tests/unit/test_uf_decoder.py
Labels: owners review ready, performance

#63 Remove unused pandas
  .github/CHANGELOG.md
  .pylintrc
  dev_requirements.txt
  doc/build_docs.rst
  doc/dev_requirements.txt
  doc/development/guide_for_devs.rst
  flamingpy/__init__.py
  flamingpy/_version.py
Labels: setup

#64 Make MPI and `mpi4py` and opt-in dependency
  .github/CHANGELOG.md
  .github/workflows/build_tests.yaml
  README.md
  dev_requirements.txt
  doc/build_docs.rst
  doc/development/guide_for_devs.rst
  doc/source/fp.rst
  flamingpy/_version.py
  flamingpy/simulations.py
Labels: bug, documentation, setup, workflow & tests

#67 [Frozen Period] Special Release, May 2022
  .github/CHANGELOG.md
  .github/workflows/upload_linux_x64.yaml
  .readthedocs.yml
  dev_requirements.txt
  doc/dev_requirements.txt
  doc/development/guide_for_devs.rst
  doc/source/fp.rst
  flamingpy/_version.py
  flamingpy/simulations.py
  flamingpy/utils/viz.py
  setup.py
Labels: special release
