Repository XanaduAI/flamingpy, pull requests merged in 2022-04, with the labels that each got.

#7 Documentation header links quick fix
  .github/ISSUE_TEMPLATE/feature_request.yaml
  doc/_static/faq.html
  doc/_static/install.html
  doc/_static/quantumErrorCorrection.html
  doc/_static/style.css
  doc/xanadu_theme/header.html
  flamingpy/_version.py
Labels: documentation, chores, owners review ready

#11 Code quality and pylint improvements to `A`
  .coveragerc
  .github/CHANGELOG.md
  .github/CONTRIBUTING.rst
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/code_of_conduct.md
  .github/pull_request_template.md
  .github/workflows/docs.yaml
  .github/workflows/format.yaml
  .github/workflows/linting.yaml
  .github/workflows/upload_linux_x64.yaml
  .gitignore
  .pylintrc
  README.md
  doc/development/contribution.rst
  flamingpy/__init__.py
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/cv/macro_reduce.py
  flamingpy/cv/ops.py
  flamingpy/examples/decoding.py
  flamingpy/examples/gkp.py
  flamingpy/utils/viz.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_decoder.py
  tests/unit/test_gkp.py
  tests/unit/test_graphstates.py
  tests/unit/test_init.py
  tests/unit/test_macro_reduce.py
  tests/unit/test_simulations.py
  tests/unit/test_surface_code.py
Labels: chores

#17 Adopt the Xanadu Sphinx Theme
  .github/CHANGELOG.md
  .gitignore
  .pylintrc
  doc/_static/faq.html
  doc/_static/favicon.ico
  doc/_static/install.html
  doc/_static/quantumErrorCorrection.html
  doc/_static/xanadu_logo.svg
  doc/conf.py
  doc/custom_directives.py
  doc/dev_requirements.txt
  doc/faq.rst
  doc/index.rst
  doc/install.rst
  doc/quantum_error_correction.rst
  doc/xanadu_theme/LICENSE
  doc/xanadu_theme/comments.html
  doc/xanadu_theme/footer.html
  doc/xanadu_theme/globaltoc.html
  doc/xanadu_theme/header.html
  doc/xanadu_theme/layout.html
  doc/xanadu_theme/localtoc.html
  doc/xanadu_theme/logo-text.html
  doc/xanadu_theme/search.html
  doc/xanadu_theme/searchbox.html
  doc/xanadu_theme/sourcelink.html
  doc/xanadu_theme/static/css/nanoscroller.css
  doc/xanadu_theme/static/jquery.js
  doc/xanadu_theme/static/jquery.min.map
  doc/xanadu_theme/static/js/bootstrap.js
  doc/xanadu_theme/static/js/bootstrap.min.js
  doc/xanadu_theme/static/js/jquery.nanoscroller.js.map
  doc/xanadu_theme/static/js/nanoscroller.min.js
  doc/xanadu_theme/static/tomorrow.css
  doc/xanadu_theme/static/tomorrow_night.css
  doc/xanadu_theme/static/xanadu.css_t
  doc/xanadu_theme/theme.conf
  flamingpy/_version.py
  flamingpy/benchmarks/simulations.py
  flamingpy/codes/surface_code.py
  flamingpy/cv/ops.py
  flamingpy/utils/viz.py
  setup.py
  tests/unit/test_surface_code.py
Labels: documentation
