Repository XanaduAI/flamingpy, pull requests merged in 2022-06, with the labels that each got.

#76 Use pylint stable version
  .github/CHANGELOG.md
  .github/workflows/linting.yaml
  dev_requirements.txt
  flamingpy/_version.py
  tests/unit/test_decoder.py
  tests/unit/test_gkp.py
  tests/unit/test_graphstates.py
  tests/unit/test_macro_reduce.py
  tests/unit/test_simulations.py
  tests/unit/test_surface_code.py
  tests/unit/test_uf_decoder.py
Labels: workflow & tests

#60 Some tests for the viz module
  .github/CHANGELOG.md
  flamingpy/_version.py
  tests/unit/test_viz.py
Labels: workflow & tests

#68 Add built-in graph states to flamingpy.utils
  .github/CHANGELOG.md
  doc/_static/classes_flamingpy.svg
  doc/_static/graph_states_thumbnail.png
  doc/_static/packages_flamingpy.svg
  doc/_static/thumbs/sphx_glr_run_graph_states_thumb.png
  doc/development/guide_for_devs.rst
  doc/source/fp.utils.rst
  doc/tutorials/run_error_correction.py
  doc/tutorials/run_graph_states.py
  doc/usage/tutorials.rst
  flamingpy/_version.py
  flamingpy/codes/graphs/egraph.py
  flamingpy/utils/graph_states.py
  flamingpy/utils/viz.py
  tests/unit/test_utils_graphstates.py
Labels: compatible feature

#78 Configuring git to handle `eol`
  .gitattributes
  .github/CHANGELOG.md
  .github/pull_request_template.md
  README.md
  doc/_ext/edit_on_github.py
  doc/tutorials/run_error_correction.py
  flamingpy/__init__.py
  flamingpy/_version.py
  flamingpy/cv/macro_reduce.py
  flamingpy/cv/ops.py
  flamingpy/decoders/mwpm/algos.py
  flamingpy/decoders/unionfind/algos.py
  flamingpy/decoders/unionfind/uf_classes.py
  flamingpy/examples/decoding.py
  flamingpy/examples/surface_code.py
  flamingpy/simulations.py
  tests/conftest.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_simulations.py
  tests/unit/test_uf_decoder.py
Labels: chores, programming conventions

#55 Add figure object to return statement of `draw` method of `EGraph`
  .github/CHANGELOG.md
  flamingpy/_version.py
  flamingpy/codes/graphs/egraph.py
  flamingpy/examples/surface_code.py
  tests/unit/test_graphstates.py
  tests/unit/test_viz.py
Labels: visualization, restructuring

#79 Increase scope of docformatter and black [unitaryhack]
  .github/CHANGELOG.md
  .github/workflows/format.yaml
  doc/_ext/edit_on_github.py
  doc/conf.py
  doc/tutorials/run_error_correction.py
  doc/tutorials/run_graph_states.py
  flamingpy/_version.py
  flamingpy/examples/surface_code.py
  flamingpy/simulations.py
  setup.py
  tests/conftest.py
  tests/unit/test_benchmarks_examples.py
  tests/unit/test_iid_noise.py
  tests/unit/test_init.py
  tests/unit/test_matching.py
  tests/unit/test_stabilizer_graph.py
  tests/unit/test_uf_decoder.py
  tests/unit/test_utils_graphstates.py
  tests/unit/test_viz.py
Labels: chores, workflow & tests, unitaryhack-accepted

#70 Restructuring unit tests with their own sub-dirs
  .github/CHANGELOG.md
  .github/workflows/build_tests.yaml
  .github/workflows/linting.yaml
  .pylintrc
  dev_requirements.txt
  doc/development/guide_for_devs.rst
  doc/index.rst
  doc/install.rst
  doc/quick_installation.rst
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/cv/gkp.py
  flamingpy/cv/macro_reduce.py
  flamingpy/cv/ops.py
  flamingpy/decoders/decoder.py
  flamingpy/decoders/unionfind/algos.py
  flamingpy/decoders/unionfind/uf_classes.py
  flamingpy/examples/decoding.py
  flamingpy/simulations.py
  flamingpy/utils/viz.py
  pytest.ini
  setup.py
  tests/benchmarks/test_benchmarks.py
  tests/cv/test_gkp.py
  tests/cv/test_macro_reduce.py
  tests/decoders/test_decoder.py
  tests/decoders/test_matching.py
  tests/decoders/test_uf_decoder.py
  tests/examples/test_examples.py
  tests/frontend/test_init.py
  tests/frontend/test_simulations.py
  tests/noise_models/test_iid_noise.py
  tests/qubit_codes/test_graphstates.py
  tests/qubit_codes/test_stabilizer_graph.py
  tests/qubit_codes/test_surface_code.py
  tests/visualization/test_viz.py
Labels: workflow & tests

#84 Making the docs more 🌟 aesthetic 🌟
  .github/CHANGELOG.md
  .gitignore
  doc/_static/classes_flamingpy.svg
  doc/_static/packages_flamingpy.svg
  doc/conf.py
Labels: documentation

#65 Skip cpp-dependent tests when dependencies not installed + minor pylint and test changes
  .github/CHANGELOG.md
  .pylintrc
  flamingpy/__init__.py
  flamingpy/_version.py
  tests/decoders/test_matching.py
  tests/utils/test_graphstate_menu.py
  tests/utils/test_viz.py
Labels: chores

#62 Refactor periodic boundaries 🍩
  .github/CHANGELOG.md
  doc/tutorials/run_error_correction.py
  flamingpy/_version.py
  flamingpy/benchmarks/decoding.py
  flamingpy/codes/surface_code.py
  flamingpy/decoders/decoder.py
  flamingpy/examples/surface_code.py
  tests/cv/test_macro_reduce.py
  tests/decoders/test_decoder.py
  tests/decoders/test_uf_decoder.py
  tests/frontend/test_simulations.py
  tests/qubit_codes/test_stabilizer_graph.py
  tests/qubit_codes/test_surface_code.py
Labels: compatible feature, chores

#57 Improvements to noise layers, including CVLayer and macronode reduction
  .github/CHANGELOG.md
  .github/workflows/linting.yaml
  .local_plt/.gitignore
  README.md
  doc/source/fp.cv.rst
  doc/source/fp.noise.rst
  doc/tutorials/run_error_correction.py
  doc/usage/getting_started.rst
  flamingpy/.sims_data/.gitignore
  flamingpy/_version.py
  flamingpy/benchmarks/decoding.py
  flamingpy/benchmarks/matching.py
  flamingpy/benchmarks/shortest_path.py
  flamingpy/cpp/cpp_mc_loop.pyx
  flamingpy/cv/__init__.py
  flamingpy/cv/macro_reduce.py
  flamingpy/cv/ops.py
  flamingpy/decoders/decoder.py
  flamingpy/examples/decoding.py
  flamingpy/examples/graphstates.py
  flamingpy/examples/macro_reduce.py
  flamingpy/noise/__init__.py
  flamingpy/noise/cv.py
  flamingpy/noise/iid.py
  flamingpy/simulations.py
  tests/cv/test_cv_ops.py
  tests/cv/test_macro_reduce.py
  tests/decoders/test_decoder.py
  tests/decoders/test_matching.py
  tests/decoders/test_uf_decoder.py
  tests/examples/test_examples.py
  tests/frontend/test_simulations.py
  tests/noise_models/test_cv_noise.py
  tests/noise_models/test_iid_noise.py
  tests/qubit_codes/test_graphstates.py
  tests/qubit_codes/test_stabilizer_graph.py
Labels: cv layer

#61 Non-cubic surface code
  .github/CHANGELOG.md
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  flamingpy/examples/surface_code.py
  tests/cv/test_cv_ops.py
  tests/cv/test_gkp.py
  tests/decoders/test_decoder.py
  tests/decoders/test_matching.py
  tests/decoders/test_uf_decoder.py
  tests/frontend/test_simulations.py
  tests/noise_models/test_cv_noise.py
  tests/qubit_codes/test_graphstates.py
  tests/qubit_codes/test_stabilizer_graph.py
  tests/qubit_codes/test_surface_code.py
Labels: compatible feature

#94 Fix typo in the installation instructions
  .github/CHANGELOG.md
  .github/pull_request_template.md
  doc/install.rst
  flamingpy/_version.py
  flamingpy/codes/surface_code.py
  tests/qubit_codes/test_surface_code.py
Labels: documentation

#96 Add FlamingPy forum and slack links to website and readme 🔗
  .github/CHANGELOG.md
  README.md
  doc/conf.py
  doc/development/guide_for_devs.rst
  doc/help/frequently_encountered_errors.rst
  doc/help/support.rst
  doc/index.rst
  flamingpy/_version.py
  flamingpy/noise/cv.py
Labels: documentation

#99 Remove unused `p_err` argument
  .github/CHANGELOG.md
  flamingpy/simulations.py
  tests/frontend/test_simulations.py
Labels: bug
